services:

    mysql:
        container_name: ${BASE_NAME}-mysql
        image: percona/percona-server:8.0
#        ports:
#            - ${MYSQL_PORT}:9200
        volumes:
            - type: bind
              source: ../../data/percona/8036
              target: /var/lib/mysql
            - type: bind
              source: ../../images/percona/8036/config/mysql/docker.cnf
              target: /etc/mysql/conf.d/docker.cnf
              read_only: false
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=sugar
            - MYSQL_PASSWORD=sugar
        command:
            - '--skip-log-bin'
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_general_ci'