services:
    phpmyadmin:
        container_name: ${BASE_NAME}-phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        volumes:
            - type: bind
              source: ../../images/phpmyadmin/themes/boodark
              target: /var/www/html/themes/boodark
            - type: bind
              source: ../../images/phpmyadmin/themes/boodark-orange
              target: /var/www/html/themes/boodark-orange
            - ../../images/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        env_file:
            - ../../images/phpmyadmin/db_password.txt
        ports:
            - ${MYADMIN_PORT}:80
        depends_on:    
            mysql:
                condition: service_healthy