services:
    oracle:
        container_name: ${BASE_NAME}-oracle
        image: gvenzl/oracle-free
        environment:
          - PUID=1000
          - PGID=1000
#          - "ORACLE_DATABASE=MIDDLEWARE"
#          - "ORACLE_RANDOM_PASSWORD=true"
          - "ORACLE_PASSWORD=test"
          - "APP_USER=test"
          - "APP_USER_PASSWORD=test"
        # Forward Oracle port
        ports:
          - ${ORACLE_PORT}:1521
        volumes:
          - oracle-data:/opt/oracle/oradata
                # Customize healthcheck script options for startup
          - type: bind
            source: ../../data/oracle/container-entrypoint-initdb.d
            target: /container-entrypoint-initdb.d 
        healthcheck:
          test: ["CMD", "healthcheck.sh"]
          interval: 10s
          timeout: 5s
          retries: 10
          start_period: 5s
          start_interval: 5s
volumes:
    oracle-data:
        name: ${STACK_NAME}-${BASE_NAME}-oracle_data
        driver: local
